version: '3.8'

services:
  cloudcustomers:
    image: anu08saini/cloudcustomers:latest
    ports:
      - '6060:6060'
    depends_on:
    - cache
    networks:
    - backend
  cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    networks:
    - backend
networks:
  backend:
    driver: bridge
