name: CI

#Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
 # Step 1: Build Job
  build:
   # The type of runner that the job will run on
     runs-on: ubuntu-latest
     
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - name: Checkout code
         uses: actions/checkout@v4
       
       - name: Setup .NET Core
         uses: actions/setup-dotnet@v3
         with:
           dotnet-version: '8.0'
           
       - name: Restore dependencies
         run: dotnet restore CloudCustomers.sln

       - name: Build Project
         run: dotnet build CloudCustomers.sln --configuration Release

 # Step 2: Docker Build Job, depends on Build Job
  docker_build:
    needs: Build
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
     
        - name: Build the Docker image
          run: docker build -t anu08saini/cloudcustomers:latest .

        - name: Log in to docker hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Push docker image to Docker Hub
          run: docker push anu08saini/cloudcustomers:latest


