name: Docker

on:
  workflow_run:
    workflows: [ "Build" ]
    types:
      - completed
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  docker_build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
    - uses: actions/checkout@v4

    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
          name: build  # Must match the artifact name from build.yml

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
     
    - name: Build the Docker image
      run: docker build -t anu08saini/cloudcustomers:latest

    - name: Log in to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push docker image to Docker Hub
      run: docker push anu08saini/cloudcustomers:latest
